### ISSUE TITLE
Questions about the training and report checkpoint

### ISSUE THREAD

**Issue by BellCHENG** [yuantianyuan01/StreamMapNet#14]
Thanks for your great work!

As the previous issue, I am also reproducing the model performance on the old-split nuScenes dataset with the baseline [config file](https://github.com/yuantianyuan01/StreamMapNet/blob/main/plugin/configs/nusc_baseline_480_60x30_30e.py) you provide. I keep all training setting the same with the informantion you provide on 8*RTX3090 GPUs, but only got ~55 mAP although I tried several times.

Could you please give me some hints about how to improve this performance to approach the 63 mAP or could you please release your training log for reference and check if I make any mistake? Thanks.

Look forward to hearing from you.

**Comment by yuantianyuan01** [comment]
Have you tried to evaluate our checkpoints? Does it reproduce the same mAP?

**Comment by BellCHENG** [comment]
> Have you tried to evaluate our checkpoints? Does it reproduce the same mAP?

Yeah, it generates the same mAP results as your report. But I can not achieve the same result but only ~55 mAP if I trained it with the config file you provide, so I would like to know if you can release the training log for me to check if there is any mistakes in my training process.

**Comment by yuantianyuan01** [comment]
Unfortunately we cannot find the training logs and we are in short of GPU resources recently. We will try to reproduce it as soon as we have enough GPU resources.

**Comment by yuantianyuan01** [comment]
Here's the training log. If you find what caused the performance gap, feel free to report it.
[20230825_015931.log](https://github.com/yuantianyuan01/StreamMapNet/files/13557587/20230825_015931.log)

**Comment by BellCHENG** [comment]
Thanks a lot for your help
