### ISSUE TITLE
different performances between code and paper

### ISSUE THREAD

**Issue by Michel-liu** [yuantianyuan01/StreamMapNet#16]
Hi~ Thank you for your great work! 
I have a question about the different performances between the code and paper. In Table 2, the AP of the new NuScenes split at 100x50m is 23.0, while the reported AP in the result of this code is 22.4. Besides, there are also many increasements than the paper. What is the reason for this phenomenon? Thanks!

**Comment by yuantianyuan01** [comment]
Hi, thank you for your interest in our work. The results reported in this repo are produced by the released code and the ones in the paper are produced by previous dev version. The performance gap of all experiments are typically below 1 mAP which is minor and might due to some bug fixes.

**Comment by Michel-liu** [comment]
OK, I get it. Thank you again for your work and quick reply!
