### ISSUE TITLE
Comparing the map_utils in this repo and the ones in MapTR

### ISSUE THREAD

**Issue by woodfrog** [yuantianyuan01/StreamMapNet#18]
Hi Tianyuan,

I noticed that your [map_utils](https://github.com/yuantianyuan01/StreamMapNet/blob/main/plugin/datasets/map_utils/) for both nuScenes and Argoverse-v2 are kind of different from the ones used in MapTR's codebase. I'm curious why the implementations are different (are there any insights, like better geometry quality?), and how these differences affect the evaluation results. For example, if MapTR or MapTR-v2 is trained and tested using your map_utils, would the results change a lot compared to using their original map pre-processing utils? 

Thank you!

**Comment by yuantianyuan01** [comment]
My data processing pipeline follows the code offered by [CVPR2023 Workshop](https://github.com/Tsinghua-MARS-Lab/Online-HD-Map-Construction-CVPR2023). It specifically handles some map errors of lane dividers in argoverse2 dataset.

**Comment by woodfrog** [comment]
Thank you for the answer!
