### ISSUE TITLE
onnx help

### ISSUE THREAD

**Issue by cedricgsh** [yuantianyuan01/StreamMapNet#24]
Thank for your amazing job. I try to get onnx model, but get this mistake, how can I fix this problem.
RuntimeError: axes_vector.size() <= input_shape.size()INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/passes/onnx/shape_type_inference.cpp":672, please report a bug to PyTorch.

**Comment by WilliamXuanYu** [comment]
I also encountered the same problem. How did you solve it?
