### ISSUE TITLE
temporal fusion

### ISSUE THREAD

**Issue by GXmmm18** [yuantianyuan01/StreamMapNet#30]
I have a question, at line 173 of StreamMapNet.py:
#Backbone
_bev_feats = self.backbone(img, img_metas=img_metas, points=points)
It seems that the prev_bev parameter (previous bev featues) is not given here. Does it mean that timing fusion is not done later? At the same time, I noticed that the is_first_frame parameter is always True. Why is this?

**Comment by yuantianyuan01** [comment]
Hi,

The temporal fusion is done at line 177, where we use a memory bank to store and update the bev features. The `is_first_frame` should not always be `true`. Please make sure you are using the correct config file, for example https://github.com/yuantianyuan01/StreamMapNet/blob/main/plugin/configs/nusc_newsplit_480_100x50_24e.py.

**Comment by GXmmm18** [comment]
thank you~
