### ISSUE TITLE
Single GPU training

### ISSUE THREAD

**Issue by alfredgu001324** [yuantianyuan01/StreamMapNet#4]
Hi, thank for the great work.

I am trying to reproduce your result using just one single GPU. But the following error occurs:
`RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.`

by running this command:
`python tools/train.py /home/guxunjia/project/StreamMapNet/plugin/configs/nusc_baseline_480_60x30_30e.py --deterministic --no-validate`

**Comment by Zhenghao97** [comment]
You should start the training by torch.distributed.launch even if you only use one gpu. What's more, according to the comment code of this repo, the bevformer backbone only support distributed training.
