### ISSUE TITLE
Model saving

### ISSUE THREAD

**Issue by alfredgu001324** [yuantianyuan01/StreamMapNet#5]
Hi, I saw that in your config file you use IterBased runner. I am wondering why this is preferred over epoch based? Also, I am wondering when the intermediate model will be saved? i.e. if the performance increase or?

**Comment by alfredgu001324** [comment]
Is it possible to put it in a EpochBased runner format so that we can see the improvements over epochs? Thanks!

**Comment by yuantianyuan01** [comment]
IterBasedRunner is more flexible and can easily support temporal training. You may try modifing the code to use EpochBasedRuuner if necessary. The checkpoint saving schedule are defined [here](https://github.com/yuantianyuan01/StreamMapNet/blob/main/plugin/configs/av2_newsplit_608_100x50_30e.py#L371).

**Comment by alfredgu001324** [comment]
@yuantianyuan01 Thanks for your clarification! Would modifying to EpochBased runner degrade the performance?

**Comment by yuantianyuan01** [comment]
It shouldn't affect the performance unless it brings additional bugs.

**Comment by alfredgu001324** [comment]
I see, thank you so much!
